services:
  mongo:
    image: mongo
    ports:
      - 27027:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./PersistentData:/data/db
    networks:
      - chatapp

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
    networks:
      - chatapp

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: YourStrong(!)Password
    networks:
      - chatapp
    volumes:
      - sql_data:/var/opt/mssql

  chatvideoapi:
    image: chatvideoapi
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - sqlserver
    networks:
      - chatapp

  chatapp:
    image: chatapp
    ports:
      - 80:80
    networks:
      - chatapp

networks:
  chatapp:
    driver: bridge
volumes:
  sql_data:
